ats {
  http.tracing {
    enabled = false
    enabled = ${?ATS_HTTP_TRACING}
    zipkin_uri = "http://127.0.0.1:9411"
    zipkin_uri = ${?ZIPKIN_URI}
    sample_rate = 1.0
    sample_rate = ${?ZIPKIN_SAMPLE_RATE}
  }
}
